version: "3"

services:
  app:
    build: ./app
    restart: always
    env_file: ./.env
    volumes:
      - ./app:/app
      - /app/node_modules # Remove this if you have pure JS dependencies
    ports:
      - $NODE_LOCAL_PORT:$NODE_DOCKER_PORT
    environment:
      - DATABASE=$DATABASE
      - USERNAME=$USERNAME
      - PASSWORD=$PASSWORD
      - DIALECT=$DIALECT
      - STORAGE=$STORAGE
      - STORAGE_TEST=$STORAGE_TEST